version: "3.9" 

services:
  db:
    image: postgres
    container_name: psqldb
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=segmentation
    ports:
      - '5432:5432'